apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
   - name: nginx
     image: nginx:latest
     command: ["env"]
     env:
      - name: DB_CONNECT
        value: https://demo:27017
     ports:
      - containerPort: 80
     readinessProbe:
       tcpSocket:
         port: 80
       initialDelaySeconds: 15
       periodSeconds: 10
     livenessProbe:
       tcpSocket:
         port: 80
       initialDelaySeconds: 15
       periodSeconds: 10
 
